export const ROOT_ROUTE = '/'
export const DASHBOARD_ROUTE = '/dashboard'
export const BROWSE_ROUTE = '/browse'
export const LOGIN_ROUTE = '/login'
export const POST_ROUTE = '/posts'
export const NEW_POST_ROUTE = '/newpost'
